[package]
name = "bitcoin-rest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
bitcoincore-rpc = "0.14.0"
bitcoin_hashes = "0.10.0"
clap = "2.33.3"